# Generated by Django 6.0.4 on 2026-05-05 09:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('taille_cm', models.FloatField(blank=True, null=True)),
                ('poids_kg', models.FloatField(blank=True, null=True)),
                ('activite', models.CharField(choices=[('bureau', 'Bureau'), ('sport', 'Sport'), ('autre', 'Autre')], max_length=100)),
                ('pathologies', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debut_session', models.DateTimeField()),
                ('fin_session', models.DateTimeField(blank=True, null=True)),
                ('duree_minutes', models.IntegerField(default=0)),
                ('device_id', models.CharField(max_length=100)),
                ('contexte', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RawMeasure',
            fields=[
                ('id_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acc_x', models.FloatField()),
                ('acc_y', models.FloatField()),
                ('acc_z', models.FloatField()),
                ('gyro_x', models.FloatField()),
                ('gyro_y', models.FloatField()),
                ('gyro_z', models.FloatField()),
                ('pitch', models.FloatField()),
                ('roll', models.FloatField()),
                ('flex_lombaire', models.FloatField()),
                ('flex_thoracique', models.FloatField()),
                ('flex_cervical', models.FloatField()),
                ('pression_ischion_g', models.FloatField()),
                ('pression_ischion_d', models.FloatField()),
                ('pression_cuisse_g', models.FloatField()),
                ('pression_cuisse_d', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='dashboard.session')),
            ],
        ),
    ]
