# Generated by Django 6.0.4 on 2026-05-05 09:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosturalAnalysis',
            fields=[
                ('id_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_posture', models.IntegerField()),
                ('deviation_dos', models.FloatField()),
                ('deviation_cou', models.FloatField()),
                ('symetrie_pression', models.FloatField()),
                ('zone_tension', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('vert', 'Vert'), ('orange', 'Orange'), ('rouge', 'Rouge')], max_length=20)),
                ('immobilite_min', models.IntegerField()),
                ('recommandation', models.TextField()),
                ('timestamp_analyse', models.DateTimeField(auto_now_add=True)),
                ('measure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.rawmeasure')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.session')),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_alerte', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('declenchee_at', models.DateTimeField(auto_now_add=True)),
                ('lue', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.posturalanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('score_moyen', models.FloatField()),
                ('progression_pct', models.FloatField()),
                ('export_pdf_url', models.URLField(blank=True, max_length=500, null=True)),
                ('genere_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
