# Generated by Django 6.0.4 on 2026-05-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_posturalanalysis_alerte_rapport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='taille_cm',
            new_name='taille',
        ),
        migrations.AlterField(
            model_name='profile',
            name='activite',
            field=models.CharField(choices=[('sedentaire', 'Sédentaire'), ('actif', 'Actif'), ('sportif', 'Sportif')], default='sedentaire', max_length=100),
        ),
    ]
